name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: analyzer_user
          POSTGRES_PASSWORD: analyzer_password
          POSTGRES_DB: analyzer
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install package with dev dependencies
        run: |
          python -m pip install --uprade pip
          pip install .[dev]

      - name: Run tests
        run: pytest --cov=analyzer --cov-report=term-missing tests/
